[package]
name = "voxels"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.17.0", features = ["derive"] }
egui = "0.26.2"
egui-winit = "0.28.1"
egui_glium = "0.26.3"
glam = { version = "0.29.0", features = ["bytemuck"] }
glium = "0.34.0"
winit = "0.29"
